# Jekyll configuration

name: B-O-B // BlekiOne Blog
description: It's all about homelab, babe.

# Url is currently only used only for the RSS feed in feed.xml
url: http://blekione.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
#baseurl: '/jekyll-clean-dark'

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: blekione
  stackoverflow: 1779488
#  linkedin:
#  instagram: ''
#  lastfm: ''
#  rss: feed.xml
  twitter: KruglikMarcin

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-116072205-1
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: blekione
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
